# Generated by Django 5.2.3 on 2025-12-10 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.IntegerField(unique=True)),
                ('ward_name', models.CharField(max_length=150)),
                ('total_voters', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('party', models.CharField(max_length=100)),
                ('party_logo', models.ImageField(upload_to='party_logos/')),
                ('candidate_photo', models.ImageField(upload_to='candidate_photos/')),
                ('vote_count', models.IntegerField(default=0)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='admin_app.ward')),
            ],
        ),
    ]
