# Generated by Django 4.2.23 on 2025-08-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_tag_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['publish_date'], name='user_app_ne_publish_cd7e39_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='user_app_ne_slug_ff3c06_idx'),
        ),
    ]
